app.use(require('../routes/user'));
app.use(require('../routes/contact'));
app.use(require('../routes/product'));
app.use(require('../routes/cart'));
app.use(require('../routes/wishlist'));
app.use(require('../routes/order'));
app.use(require('../routes/image'));
app.use(require('../routes/category'));
app.use(require('../routes/CustomerReview'));